# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_frameworks!

def shared_pods
    pod 'Alamofire'
    pod 'R.swift'
    pod 'DateParser'
    pod 'Neon'
    pod 'Font-Awesome-Swift'
    pod 'TAOverlay'
    pod 'SDWebImage'
    pod 'SwiftLint'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'AlertHelperKit', :git => 'https://github.com/keygx/AlertHelperKit'
end

target 'OKJUX' do
    shared_pods
    pod 'OHHTTPStubs'
    pod 'OHHTTPStubs/Swift'
end

target 'OKJUXTests' do
    shared_pods
end

target 'OKJUXUITests' do
    shared_pods

end
