# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OKJUX' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OKJUX
  pod 'Alamofire'
  pod 'R.swift'
  pod 'DateParser'

  target 'OKJUXTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OKJUXUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
